### ISSUE TITLE
全局数据问题

### ISSUE THREAD

**Issue by maik-he** [wxxsw/SwiftUI-WeChat#10]
你采用的是全局的navigationView，通过更新store的状态去改变navigationView的状态，这个会存在问题，特别是在onAppear里面进行网络请求刷新数据，会导致界面数据丢失。初步看原因就是在因为在onAppear里面更新的store.hiddenNavBar的状态，导致所有界面多次刷新。

**Comment by wxxsw** [comment]
你好，确认一下，你的意思是四个 `Tab` 主界面 `onAppear` 里的 `self.root.tabNavigationHidden = true`，会导致所有界面多次刷新吗？

能说下你的测试步骤吗？是否去掉那行代码就没问题了？
