### ISSUE TITLE
https://github.com/wxxsw/Extension是不是设置为私有库了?

### ISSUE THREAD

**Issue by seasonZhu** [wxxsw/SwiftUI-WeChat#11]
https://github.com/wxxsw/Extension是不是设置为私有库了?
使用Swift Packages工具已经拉不下来了.
我直接去这个网址是404,没有这个包依赖,不能编译过呀

**Comment by wxxsw** [comment]
你好，`SwiftUI-Wechat` 已经不依赖这个库了，并且这个库已经删除了，因为目前存在的价值比较小，里面的扩展已经直接挪出来直接放到项目里了，你可以下载最新的项目试一下。

**Comment by seasonZhu** [comment]
> 你好，`SwiftUI-WeChat` 已经不依赖这个库了，并且这个库已经删除了，因为目前存在的价值比较小，里面的扩展已经直接挪出来直接放到项目里了，你可以下载最新的项目试一下。

好的,谢谢,因为一直都在关注你这个项目,最近刚拉过一把,我再试试
