### ISSUE TITLE
如何在SwiftUI中实现navigationController.popToRootViewControoler的功能

### ISSUE THREAD

**Issue by damonZDM** [wxxsw/SwiftUI-WeChat#16]
NavigationLink多个View之后，无法直接返回根视图。
我在您项目的基础上做了个人详情页，想在用户信息页面删除用户后快速返回跟视图，但是没有找到合适的方法。
在微信中ChatView始终只有一个，比如从群聊进入用户页面，再点击发送消息到聊天也，则NavigationController中的其他ChildViewController会被移除，再进入ChatView页面，现在也无法在SwiftUI上实现

**Comment by wxxsw** [comment]
`NavigationLink` 第二个参数 `isActive` 可以用来实现快速返回根视图。

参考：https://stackoverflow.com/questions/57334455/swiftui-how-to-pop-to-root-view
