### ISSUE TITLE
SwiftUI中ScollView嵌套LazyVStack代替List会出现卡顿

### ISSUE THREAD

**Issue by damonZDM** [wxxsw/SwiftUI-WeChat#17]
SwiftUI2.0中List的separator无法隐藏，但是使用ScollView嵌套LazyVStack代替List会在显示图片视频等文件时出现较明显的卡顿，有更好的方案吗？

**Comment by wxxsw** [comment]
你的意思是如果用 `List` 就不卡，用 `ScrollView` 和 `LazyVStack` 才开始卡的吗？

因为出现明显卡顿，也有可能是图片解码开销大的缘故，如果使用 `Kingfisher` 或者 `SDWebImage`，也许性能会有所改善。

但如果用 `List` 就不卡的话，那就有待考证了。
