### ISSUE TITLE
SwiftUI是只支持ios13以上版本吗？

### ISSUE THREAD

**Issue by feifeiwuxian** [wxxsw/SwiftUI-WeChat#2]
希望有个官方的说明，网上都乱七八糟的。求大神指点。

**Comment by wxxsw** [comment]
是的，只支持 iOS 13 及以上

**Comment by frankxiongsir** [comment]
![image](https://user-images.githubusercontent.com/11530882/117761587-2dcad380-b25a-11eb-9914-9669ade35d28.png)
