### ISSUE TITLE
navigationlink 只能跳转一次

### ISSUE THREAD

**Issue by maik-he** [wxxsw/SwiftUI-WeChat#8]
我看项目里面列表也有这个问题，点击跳返回后，不能再次点击跳转一定要点击另一条跳转后，才能点击之前的一条数据进行跳转，你有解决这个问题吗

**Comment by wxxsw** [comment]
你好，这是模拟器的 bug，真机运行就没问题了

**Comment by maik-he** [comment]
非常感谢，我确实也没用真机跑，还以为真机是一样的。苹果bug真是越来越多了。
